# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/evr',
                'doc_host': 'https://bilalcodehub.github.io',
                'git_url': 'https://github.com/bilalcodehub/evr',
                'lib_path': 'evr'},
  'syms': {'evr.core': {'evr.core.foo': ('core.html#foo', 'evr/core.py')}}}
